version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "modami-stg-image-utils-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r3ah7ysx7soi"
s3_prefix = "modami-stg-image-utils-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

version = 0.1
[release]
[release.deploy]
[release.deploy.parameters]
stack_name = "modami-stg-image-utils-stack-release"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r3ah7ysx7soi"
s3_prefix = "modami-stg-image-utils-stack-release"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
profile = "modami-stg-eks-admin"

version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "modami-pro-image-utils-stack"
region = "us-east-1"
s3_prefix = "modami-pro-image-utils-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
profile = "modami-pro-eks-admin"