AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple SAM Template

Resources:

  CloudFrontImageOriginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cloudfront-image-origin-request/
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole

