// ErrorCode mirrors the apperror.Code constants from the Go services.
// Keep in sync with pkg/apperror/code.go.
export enum ErrorCode {
  // Client errors (4xx)
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  CONFLICT = 'CONFLICT',
  GONE = 'GONE',
  PRECOND_FAILED = 'PRECONDITION_FAILED',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA = 'UNSUPPORTED_MEDIA_TYPE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNPROCESSABLE = 'UNPROCESSABLE_ENTITY',
  LOCKED = 'LOCKED',
  FAILED_DEPENDENCY = 'FAILED_DEPENDENCY',
  PRECOND_REQUIRED = 'PRECONDITION_REQUIRED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Server errors (5xx)
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  BAD_GATEWAY = 'BAD_GATEWAY',
  SERVICE_UNAVAIL = 'SERVICE_UNAVAILABLE',
  TIMEOUT = 'TIMEOUT',

  // Infrastructure errors
  CACHE_MISS = 'CACHE_MISS',
  CACHE_ERROR = 'CACHE_ERROR',
  MESSAGE_BUS = 'MESSAGE_BUS_ERROR',
}
