name: Deploy services
run-name: ${{ github.ref_name }}

on:
  pull_request:
    types:
      - closed
      # - synchronize
      # - opened
    branches:
      - develop
      - internal
      - staging
      - release/*

permissions:
  contents: read    # This is required for actions/checkout
  id-token: write   # This is required for requesting the JWT
  pull-requests: read # This is required for action dorny/paths-filter@v2
  repository-projects: read

jobs:
  build_services_dev:
    name: Build Services for Develop
    if: ${{ github.base_ref == 'develop' }}
    uses: ./.github/workflows/_service_builder.yaml
    with:
      environment: develop
      service_env: dev
    secrets: inherit
    
  build_services_internal:
    name: Build Services for Internal
    if: ${{ github.base_ref == 'internal' }}
    uses: ./.github/workflows/_service_builder.yaml
    with:
      environment: internal
      service_env: itn
    secrets: inherit

  build_services_staging:
    name: Build Services for Staging
    if: ${{ github.base_ref == 'staging' }}
    uses: ./.github/workflows/_service_builder.yaml
    with:
      environment: staging
      service_env: stg
    secrets: inherit

  build_services_release:
    name: Build Services for Release
    if: startsWith(github.base_ref, 'release/')
    uses: ./.github/workflows/_service_builder.yaml
    with:
      environment: release
      service_env: rel
    secrets: inherit
    